version: "3"

services:
  api:
    container_name: chatgpt
    ports: #This is used to map the container’s ports to the host machine.
      - 3080:3080
    depends_on:
      - mongodb
    image: node-api # Comment this & uncomment below to build from docker hub image
    build:
      context: /var/www/html/chatgpt/
      target: node-api
    # image: chatgptclone/app:latest # Uncomment this & comment above to build from docker hub image
    restart: always
    env_file:
      - ./api/.env
    environment:
      - HOST=0.0.0.0
      - NODE_ENV=production
      - MONGO_URI=mongodb://mongodb:27017/chatgpt-clone
      # - CHATGPT_REVERSE_PROXY=http://host.docker.internal:8080/api/conversation # if you are hosting your own chatgpt reverse proxy
      - MEILI_HOST=http://meilisearch:7700
      - MEILI_HTTP_ADDR=meilisearch:7700
    volumes:
      - /client/node_modules
      - ./api:/api
      - /api/node_modules

  mongodb:
    container_name: chat-mongodb
    ports:
      - 27018:27017
    image: mongo
    restart: always
    volumes:
      - /var/www/html/services_data/data/data-node:/data/db
    command: mongod --noauth
    environment:
      TZ: Asia/Tehran

  meilisearch:
    container_name: chat-meilisearch
    image: getmeili/meilisearch:v1.0
    ports:
      - 7700:7700
    env_file:
      - ./api/.env
    environment:
      - MEILI_HOST=http://meilisearch:7700
      - MEILI_HTTP_ADDR=meilisearch:7700
    volumes:
      - /var/www/html/services_data/data/meili_data:/meili_data

  chatgpt_v2:
    build:
      context: /var/www/html/chatgpt_v2/
    container_name: chatgpt_v2
    restart: always
    expose: #This is used to map the container’s ports to the host machine.
      - "3000"
    environment:
      - "OPENAI_API_KEY=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"

  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: always
    ports: #This is used to map the container’s ports to the host machine.
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d/:/etc/nginx/conf.d/
      - ./nginx/certificates/:/etc/ssl/
      - ./nginx/log/:/var/log/nginx/
